-- ==============================================================================
-- MOHAMED EBRAHIM PORTFOLIO — IDEMPOTENT DATABASE SEED SCRIPT
-- Run this script in the Supabase SQL Editor to safely populate initial data.
-- All INSERT statements use ON CONFLICT DO NOTHING (safe to run multiple times).
-- ==============================================================================

-- INITIAL SEED DATA
-- ==============================================================================

INSERT INTO public.site_settings (id, site_title, contact_email, whatsapp_number, cv_url)
VALUES ('global', 'Mohamed Ebrahim | Data Analyst & ML Engineer', 'mhmd_ebrahim_1@outlook.com', '201093556456', '/Mohamed-Ebrahim-CV.pdf')
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.hero (id, name, full_name, title, location, status)
VALUES ('main', 'Mohamed Ebrahim', 'Mohamed Ebrahim Hamed', 'Data Analyst & ML Engineer', 'Mansoura, Egypt', 'Open to internships & freelance opportunities')
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.about (id, university, degree, graduation_year, location)
VALUES ('main', 'Kafr El-Sheikh University', 'B.Sc. Artificial Intelligence', '2023 – 2027', 'Mansoura, Egypt')
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.social_links (id, platform, label, url, icon, color, active, display_order)
VALUES
    ('linkedin', 'LinkedIn', 'LinkedIn', 'https://www.linkedin.com/in/mhmd-ebrahim1/', 'Linkedin', '#0ea5e9', true, 1),
    ('github', 'GitHub', 'GitHub', 'https://github.com/mhmd-ebrahim-1', 'Github', '#ffffff', true, 2),
    ('whatsapp', 'WhatsApp', 'WhatsApp', 'https://wa.me/201093556456?text=Hello%20Mohamed%2C%20I%20saw%20your%20portfolio%20and%20would%20like%20to%20discuss%20a%20project%20%2F%20opportunity.', 'WhatsAppIcon', '#00f5d4', true, 3),
    ('twitter', 'Twitter', 'X (Twitter)', 'https://x.com/mhmd_ebrahim_1', 'Twitter', '#38bdf8', true, 4),
    ('instagram', 'Instagram', 'Instagram', 'https://www.instagram.com/mhmd_ebrahim_1', 'Instagram', '#f43f5e', true, 5)
ON CONFLICT (id) DO NOTHING;

-- Seed Services
INSERT INTO public.services (id, title, short_desc, icon, accent, tech, deliverables, cta, email_subject, display_order, published)
VALUES
    ('data-analysis-eda', 'Data Analysis & EDA', 'Transform raw, unstructured, or messy business datasets into clean, structured data with exploratory statistical insights and visual distributions.', 'BarChart3', '#0ea5e9', '["Python", "Pandas", "NumPy", "Data Cleaning", "EDA", "Statistical Analysis"]'::JSONB, '["In-depth exploratory data analysis (EDA)", "Automated data cleaning & outlier handling scripts", "Summary statistic profiling & hypothesis testing", "Executive visual summaries in Matplotlib/Seaborn"]'::JSONB, 'Discuss Data Analysis', 'Data Analysis Project Inquiry', 1, true),
    ('power-bi-dashboards', 'Power BI & Business Intelligence', 'Design interactive, production-ready Power BI reporting dashboards with custom DAX calculations, dimensional star schemas, and automated KPI tracking.', 'LayoutDashboard', '#00f5d4', '["Power BI", "DAX", "Data Modeling", "Star Schema", "KPI Design", "Business Reporting"]'::JSONB, '["Interactive multi-page executive dashboards", "Complex DAX measures and time-intelligence calculations", "Robust dimensional data models (Fact & Dimension tables)", "Automated refresh pipelines and user-friendly filters"]'::JSONB, 'Request a Dashboard', 'Power BI Dashboard Request', 2, true),
    ('sql-database-analysis', 'SQL & Database Analytics', 'Write optimized SQL queries for complex joins, aggregations, window functions, and data extraction across relational databases and warehouses.', 'Database', '#38bdf8', '["PostgreSQL", "SQL Server", "Snowflake SQL", "Window Functions", "Data Extraction"]'::JSONB, '["Complex analytical queries and subqueries", "Window functions for rolling metrics and rankings", "Data validation, deduplication, and staging logic", "Relational schema inspection and query tuning"]'::JSONB, 'Discuss Database Project', 'SQL & Database Project Inquiry', 3, true),
    ('machine-learning-solutions', 'Machine Learning Solutions', 'End-to-end predictive modeling systems spanning data preparation, feature engineering, model selection, hyperparameter tuning, and cross-validation.', 'BrainCircuit', '#a78bfa', '["Scikit-learn", "TensorFlow", "Feature Engineering", "Classification", "Regression"]'::JSONB, '["Custom predictive models for business classification/regression", "Feature engineering and selection pipelines", "Comprehensive evaluation with ROC-AUC, F1, Precision/Recall, RMSE", "Inference scripts ready for deployment or batch jobs"]'::JSONB, 'Build an ML Model', 'Machine Learning Project Inquiry', 4, true),
    ('ai-nlp-rag-systems', 'AI, NLP & RAG Systems', 'Develop domain-specific retrieval-augmented generation (RAG) applications, custom document search engines, semantic question-answering, and LLM pipelines.', 'Bot', '#fb923c', '["Python", "RAG", "NLP", "Ollama", "TF-IDF / Embeddings", "Context Caching", "Flask"]'::JSONB, '["Document ingestion and chunking pipelines", "Hybrid semantic and keyword retrieval architectures", "Local LLM integration with fallback mechanisms", "Context-aware question-answering APIs with source attribution"]'::JSONB, 'Discuss AI & RAG', 'AI & RAG System Project Inquiry', 5, true),
    ('computer-vision', 'Computer Vision & Object Detection', 'Design real-time visual classification, multi-class object detection, and CNN-based image recognition systems for edge or web applications.', 'Eye', '#f43f5e', '["OpenCV", "YOLOv8", "PyTorch", "CNNs", "Image Classification", "Real-Time Video"]'::JSONB, '["Object detection and multi-class classification models", "Real-time video inference pipelines with OpenCV", "Dataset preprocessing, augmentation, and annotation scripts", "REST API integration for image inference"]'::JSONB, 'Discuss Vision System', 'Computer Vision Project Inquiry', 6, true),
    ('data-engineering-big-data', 'Data Engineering & Pipelines', 'Architect reproducible batch data pipelines, distributed transformations, Dockerized multi-service workflows, and cloud warehouse storage.', 'Cpu', '#34d399', '["PySpark", "Hadoop HDFS", "Apache Airflow", "Snowflake", "Docker", "ETL"]'::JSONB, '["Distributed PySpark data transformation scripts", "Apache Airflow DAGs for automated workflow scheduling", "Staging and star-schema loading into Snowflake", "Docker Compose multi-container pipeline environments"]'::JSONB, 'Discuss Data Engineering', 'Data Engineering Project Inquiry', 7, true)
ON CONFLICT (id) DO NOTHING;

-- Seed Skills
INSERT INTO public.skills (domain_key, domain_title, domain_description, accent, skills, display_order)
VALUES
    ('analytics', 'Data Analytics & BI', 'Transforming raw structured data into clean models, exploratory insights, and executive KPIs.', '#0ea5e9', '["Python", "SQL", "Pandas", "NumPy", "Power BI", "DAX", "Data Cleaning", "EDA", "Matplotlib", "Seaborn", "PostgreSQL"]'::JSONB, 1),
    ('ml', 'Machine Learning', 'Developing and evaluating predictive algorithms, feature engineering, and statistical modeling.', '#00f5d4', '["Scikit-learn", "TensorFlow", "PyTorch", "Keras", "Feature Engineering", "Model Evaluation", "Cross-Validation", "Gradient Descent", "Regression & Classification"]'::JSONB, 2),
    ('ai_nlp', 'AI, NLP & GenAI', 'Architecting semantic retrieval systems, retrieval-augmented generation (RAG), and language models.', '#a78bfa', '["NLP", "RAG Architecture", "LLMs", "Prompt Engineering", "TF-IDF & Semantic Search", "Transformers", "Ollama", "Context Caching"]'::JSONB, 3),
    ('vision', 'Computer Vision', 'Image classification, real-time object detection, facial emotion analysis, and edge vision pipelines.', '#fb923c', '["OpenCV", "YOLOv8", "CNN Architectures", "Image Classification", "Real-Time Video Inference", "Edge Prototyping"]'::JSONB, 4),
    ('data_eng', 'Data Engineering', 'Building resilient distributed data processing, automated orchestration, and cloud warehouses.', '#38bdf8', '["PySpark", "Hadoop HDFS", "Apache Airflow", "Snowflake", "Docker", "ETL Pipelines", "Data Warehousing", "Star Schema"]'::JSONB, 5),
    ('dev_tools', 'Development & Platforms', 'Robust software engineering foundations, containerization, reproducible experiments, and version control.', '#f43f5e', '["Git", "GitHub", "Docker", "Linux / Bash", "Jupyter", "VS Code", "Flask", "REST APIs", "C++", "Arduino"]'::JSONB, 6)
ON CONFLICT (domain_key) DO NOTHING;

-- Seed Experience
INSERT INTO public.experience (id, role, organization, location, start_date, end_date, current_position, description, technologies, display_order, published)
VALUES
    (1, 'Generative AI & LLM Applications Trainee', 'Information Technology Institute (ITI) — NVIDIA DLI', 'Egypt', 'Nov 2025', 'Dec 2025', false, 'Completed intensive technical training on modern LLM architectures, prompt engineering patterns, and retrieval-augmented generation (RAG). Built end-to-end retrieval pipelines and developed Python/NLP modules for domain-specific question answering.', '["LLMs", "RAG", "Prompt Engineering", "Python", "NLP", "Ollama"]'::JSONB, 1, true),
    (2, 'Data Analysis Intern', 'National Telecommunication Institute (NTI)', 'Egypt', 'Jun 2025', 'Jul 2025', false, 'Conducted exploratory data analysis and statistical evaluation on telecom customer and operational datasets using Python and SQL. Built classification models for churn and segment prediction, generated data-driven reports, and presented visual insights.', '["Python", "SQL", "Machine Learning", "Data Analysis", "EDA", "Statistical Profiling"]'::JSONB, 2, true),
    (3, 'Data Science Member', 'Microsoft Student Club — KFS', 'Egypt', 'Oct 2025', 'Dec 2025', false, 'Collaborated on data-driven projects, machine learning challenges, and community workshops. Led peer sessions on Python data analysis, predictive modeling concepts, and Power BI report design.', '["Data Science", "Machine Learning", "Power BI", "Collaboration", "Python"]'::JSONB, 3, true),
    (4, 'Power BI Trainee', 'Microsoft Student Club — KFS', 'Egypt', 'Mar 2025', 'May 2025', false, 'Designed multi-page interactive Power BI dashboards, structured relational dimensional data models, and implemented DAX measures for executive KPI tracking and business intelligence reporting.', '["Power BI", "DAX", "Data Modeling", "Business Intelligence", "KPI Design"]'::JSONB, 4, true),
    (5, 'AI Committee Member', 'Mansoura Robotics Club', 'Mansoura, Egypt', 'Jun 2024', 'May 2025', false, 'Researched and integrated artificial intelligence and computer vision algorithms into robotics systems. Collaborated with embedded engineering teams on sensor data processing and model deployment.', '["AI", "Computer Vision", "Python", "Robotics Integration", "Teamwork"]'::JSONB, 5, true),
    (6, 'Machine Learning Member', 'IEEE Kafrelshiekh Student Branch', 'Egypt', 'Oct 2024', 'Feb 2025', false, 'Developed machine learning models for community challenges, participated in technical peer reviews, and supported university workshops introducing undergraduate students to data science tools.', '["Machine Learning", "Python", "Scikit-Learn", "Data Preprocessing"]'::JSONB, 6, true)
ON CONFLICT (id) DO NOTHING;

-- Seed Projects
INSERT INTO public.projects (id, slug, title, category, category_label, accent, short_desc, value_prop, cover_image, github, live, featured, published, display_order, tech, tags)
VALUES
    (1, 'financial-market-pipeline', 'Financial Market Big Data Pipeline', 'data', 'DATA ENGINEERING', '#38bdf8', 'Production-style end-to-end pipeline for financial market analytics. Ingests daily OHLCV market data from Yahoo Finance into HDFS, executes distributed transformations with PySpark, loads a star schema in Snowflake, and feeds an analytical Power BI dashboard, all orchestrated via Dockerized Apache Airflow.', 'End-to-end market data pipeline orchestrating ingestion, distributed transformation, warehouse modeling, and business intelligence.', 'projects/financial-market-dashboard.png', 'https://github.com/mhmd-ebrahim-1/financial-market-pipeline', null, true, true, 1, '["Python", "PySpark", "HDFS", "Airflow", "Snowflake", "Power BI", "Docker"]'::JSONB, '["Python", "PySpark", "HDFS", "Airflow", "Snowflake", "Power BI", "Docker"]'::JSONB),
    (2, 'rag-ksuai', 'AI Faculty Regulations Assistant', 'ai', 'AI & NLP', '#00f5d4', 'Arabic-first RAG assistant for Kafr El-Sheikh University Faculty of AI regulations. Employs hybrid retrieval combining TF-IDF and keyword scoring with intent filtering, optional local Ollama generation, source snippet citations, caching, and retrieval-only fallback.', 'Arabic-first RAG assistant delivering instant, citation-backed academic regulation answers with local LLM inference.', 'projects/rag-ksuai-ui.png', 'https://github.com/mhmd-ebrahim-1/RAG_KSUAI', null, true, true, 2, '["Python", "RAG", "NLP", "TF-IDF", "Flask", "Ollama"]'::JSONB, '["Python", "RAG", "NLP", "TF-IDF", "Flask", "Ollama"]'::JSONB),
    (3, 'fruit-classification', 'Fruit Classification & Quality System', 'ai', 'COMPUTER VISION', '#fb923c', 'Deep learning system for real-time fruit type and quality classification. Evaluates 28 classes across 14 fruit varieties in both healthy and rotten states, featuring a web interface, Flutter mobile app, Flask API, SQLite logging, and Arduino physical sorting integration.', 'Multi-class deep learning vision system classifying fruit varieties and freshness across web, mobile, and hardware.', 'projects/fruit-classification-arch.png', 'https://github.com/mhmd-ebrahim-1/fruit-classification', null, true, true, 3, '["Python", "YOLOv8", "PyTorch", "OpenCV", "Flask", "Flutter", "Arduino"]'::JSONB, '["Python", "YOLOv8", "PyTorch", "OpenCV", "Flask", "Flutter", "Arduino"]'::JSONB),
    (4, 'healthcare-analytics', 'Healthcare Analytics Dashboard', 'data', 'DATA ANALYTICS', '#0ea5e9', 'Healthcare analytics project analyzing patient demographics, physician utilization, appointment volume, departmental revenue, and clinic expenses. Combines Python and SQL data preparation with an interactive Power BI reporting dashboard.', 'Comprehensive hospital operations and revenue intelligence platform connecting SQL processing with executive Power BI reports.', 'projects/healthcare-analytics.svg', 'https://github.com/mhmd-ebrahim-1/Healthcare-Analytics', null, true, true, 4, '["Python", "SQL", "Pandas", "Power BI", "PostgreSQL", "DAX"]'::JSONB, '["Python", "SQL", "Pandas", "Power BI", "PostgreSQL", "DAX"]'::JSONB),
    (5, 'vibecheck', 'VibeCheck — Sentiment Analyzer', 'dev', 'NLP & MOBILE', '#a78bfa', 'Android application for text and voice-based sentiment and emotion analysis with immediate visual feedback. Designed to make natural language understanding accessible through an intuitive mobile interface.', 'Accessible mobile text and speech sentiment classifier delivering instant emotion insights.', 'projects/vibecheck.svg', 'https://github.com/mhmd-ebrahim-1/VibeCheck', null, false, true, 5, '["Kotlin", "Android", "NLP", "Voice API"]'::JSONB, '["Kotlin", "Android", "NLP", "Voice API"]'::JSONB),
    (6, 'emotion-detection', 'Real-Time Facial Emotion Recognition', 'ai', 'COMPUTER VISION', '#f43f5e', 'Computer vision project for recognizing human facial emotions from live video streams using a CNN model trained with Keras/TensorFlow and an OpenCV real-time inference pipeline.', 'Deep learning facial emotion classifier running live inference through OpenCV video streams.', 'projects/emotion-detection.svg', 'https://github.com/mhmd-ebrahim-1/emotion-detection-project', null, false, true, 6, '["Python", "TensorFlow", "OpenCV", "CNN", "Keras"]'::JSONB, '["Python", "TensorFlow", "OpenCV", "CNN", "Keras"]'::JSONB),
    (7, 'movie-recommendation', 'Movie Recommendation Engine', 'ai', 'MACHINE LEARNING', '#818cf8', 'Algorithmic recommendation engine implementing regularized Non-negative Matrix Factorization (NMF) with custom Gradient Descent from scratch using Python and NumPy, without depending on high-level ML framework black boxes.', 'Recommender system implementing regularized Non-negative Matrix Factorization from scratch using pure NumPy.', 'projects/movie-recommendation.svg', 'https://github.com/mhmd-ebrahim-1/MovieRecommendation', null, false, true, 7, '["Python", "NumPy", "NMF", "Gradient Descent", "Linear Algebra"]'::JSONB, '["Python", "NumPy", "NMF", "Gradient Descent", "Linear Algebra"]'::JSONB),
    (8, 'foodmart-analytics', 'FoodMart Retail Analysis', 'data', 'BUSINESS INTELLIGENCE', '#34d399', 'Business intelligence dashboard evaluating retail store performance, analyzing historical sales trends, product category revenues, and customer purchasing patterns through interactive Power BI reports.', 'Executive retail performance dashboard analyzing sales trends, customer segments, and store margins.', 'projects/foodmart-analytics.png', 'https://github.com/mhmd-ebrahim-1/FoodMart-Retail-Analysis', null, false, true, 8, '["Power BI", "Pandas", "DAX", "Excel", "Data Modeling"]'::JSONB, '["Power BI", "Pandas", "DAX", "Excel", "Data Modeling"]'::JSONB),
    (9, 'cnc-plotter', 'Arduino CNC Plotter', 'dev', 'EMBEDDED SYSTEMS', '#f59e0b', 'Hardware-software prototyping project featuring an Arduino-controlled dual-axis stepper motor plotter. Interprets standard G-code commands for automated precision vector drawing and educational demonstrations.', 'Precision dual-axis drawing machine interpreting G-code for hardware vector plotting.', 'projects/cnc-plotter.svg', 'https://github.com/mhmd-ebrahim-1/CNC-Plotter', null, false, true, 9, '["Arduino", "C++", "G-code", "Stepper Motors", "Hardware"]'::JSONB, '["Arduino", "C++", "G-code", "Stepper Motors", "Hardware"]'::JSONB)
ON CONFLICT (id) DO NOTHING;

-- Seed Certificates
INSERT INTO public.certificates (id, slug, title, issuer, issuer_short, date, credential_id, credential_url, cover_image, category, category_label, accent, skills, featured, published, display_order)
VALUES
    (1, 'cert-nti-data', 'Advanced Data Analytics', 'National Telecommunication Institute (NTI)', 'NTI / ITIDA', 'Jun 29 – Jul 24, 2025', 'Student ID: 164771', null, 'certificates/nti-advanced-data-analytics.webp', 'top', 'Certification', '#e31e24', '["Data Analytics", "Python", "SQL", "Machine Learning", "Freelancing"]'::JSONB, true, true, 1),
    (2, 'cert-quantium', 'Data Analytics Job Simulation', 'Quantium / Forage', 'Quantium', 'Dec 25, 2025', '694d3cd139ff7eaad9d3c8e4', null, 'certificates/quantium-data-analytics-simulation.webp', 'top', 'Certification', '#111111', '["Data Analytics", "Customer Analytics", "Experimentation", "Commercial Application"]'::JSONB, true, true, 2),
    (3, 'cert-nvidia-genai', 'NVIDIA DLI Summer Training Program: Generative AI', 'ITI / NVIDIA DLI', 'NVIDIA DLI', 'Nov 16 – Dec 3, 2025', null, null, 'certificates/nvidia-iti-generative-ai.webp', 'top', 'Certification', '#76b900', '["Generative AI", "LLMs", "Prompt Engineering", "RAG", "Python"]'::JSONB, true, true, 3),
    (4, 'cert-nvidia-dl', 'Getting Started with Deep Learning', 'NVIDIA DLI', 'NVIDIA DLI', 'Dec 18, 2025', 'Le-drRAIRdUMwXFUtwcXeQ', null, 'certificates/nvidia-deep-learning.webp', 'top', 'Certification', '#76b900', '["Deep Learning", "Neural Networks", "Computer Vision"]'::JSONB, true, true, 4),
    (5, 'cert-huawei-ai', 'HCIA-AI V3.5 Course', 'Huawei Talent Online', 'Huawei', 'Sep 23, 2024', 'EBG20240923005280', null, 'certificates/huawei-hcia-ai.webp', 'top', 'Certification', '#ea3223', '["AI", "Machine Learning", "Deep Learning", "Huawei ICT"]'::JSONB, true, true, 5),
    (6, 'cert-msft-ai', 'Introduction to AI & Generative AI', 'Microsoft Egypt / MCIT', 'Microsoft', 'Oct 19–21, 2025', null, null, 'certificates/microsoft-ai-generative-ai.webp', 'top', 'Certification', '#0067b8', '["AI Fundamentals", "Generative AI", "Azure AI"]'::JSONB, true, true, 6),
    (7, 'cert-kaggle-ml', 'Intro to Machine Learning', 'Kaggle', 'Kaggle', 'Sep 14, 2025', null, null, 'certificates/kaggle-intro-machine-learning.webp', 'important', 'Certification', '#20beff', '["Machine Learning", "Scikit-Learn", "Model Validation", "Python"]'::JSONB, false, true, 7),
    (8, 'cert-hackerrank-sql', 'SQL (Basic)', 'HackerRank', 'HackerRank', 'Mar 18, 2025', 'DCE4F38589DC', null, 'certificates/hackerrank-sql-basic.webp', 'important', 'Certification', '#00a878', '["SQL", "Relational Databases", "Data Querying"]'::JSONB, false, true, 8),
    (9, 'cert-hackerrank-py', 'Python (Basic)', 'HackerRank', 'HackerRank', 'Mar 18, 2025', '0A9E2E57DEC0', null, 'certificates/hackerrank-python-basic.webp', 'important', 'Certification', '#00a878', '["Python", "Algorithms", "Data Structures"]'::JSONB, false, true, 9),
    (10, 'cert-maharatech-dl', 'Introduction to Deep Learning', 'MaharaTech / ITI', 'MaharaTech', 'Jan 22, 2026', '0Orw5rdCbs', null, 'certificates/maharatech-deep-learning.webp', 'important', 'Certification', '#b51f2b', '["Deep Learning", "Neural Networks", "Optimization"]'::JSONB, false, true, 10),
    (11, 'cert-maharatech-py', 'Python Programming Basics', 'MaharaTech / ITI', 'MaharaTech', 'Sep 18, 2024', 'N5xhBCJbJE', null, 'certificates/maharatech-python-basics.webp', 'important', 'Certification', '#b51f2b', '["Python", "Programming Fundamentals"]'::JSONB, false, true, 11),
    (12, 'cert-itida-gigs', 'ITIDA Gigs — Freelance Training Program', 'ITIDA / eYouth', 'ITIDA', '2025', null, null, 'certificates/itida-gigs-freelance.webp', 'important', 'Certification', '#0085b7', '["Freelancing", "Client Communication", "Project Delivery"]'::JSONB, false, true, 12),
    (13, 'cert-anthropic-claude', 'Claude 101', 'Anthropic', 'Anthropic', '2025', null, null, 'certificates/claude-101.webp', 'important', 'Certification', '#d97757', '["Claude", "Generative AI", "Prompt Design", "AI Fluency"]'::JSONB, false, true, 13),
    (14, 'cert-eyouth-excel', 'Data Analysis Using Excel', 'eYouth Business / IAO', 'eYouth', 'Oct 6, 2025', 'c9d3d632a96e4ba996a87255a1eb0666', null, 'certificates/eyouth-data-analysis-excel.webp', 'important', 'Certification', '#1f6fb2', '["Excel", "Data Analysis", "Spreadsheets", "Business Analytics"]'::JSONB, false, true, 14),
    (15, 'cert-udemy-bootcamp', 'Data Analysis BootCamp', 'Udemy', 'Udemy', 'Nov 29, 2025', 'UC-6b663724-9604-4faa-9046-7fb8d960d087', null, 'certificates/udemy-data-analysis-bootcamp.webp', 'important', 'Certification', '#a435f0', '["Data Analysis", "Python", "Data Cleaning", "Visualization"]'::JSONB, false, true, 15)
ON CONFLICT (id) DO NOTHING;
